services:
  redis:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: arolitec/redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
      - ./redis.conf:/etc/redis/redis.conf
      - ./logs:/var/log/redis
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges:true

volumes:
  redis:

networks:
  default:
    name: redis